[package]
name = "gmtrade-builder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
base64 = "0.22"
bincode = "1"
gmsol-sdk = { version = "0.9.0", features = ["serde"] }
gmsol-solana-utils = "0.9.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
solana-sdk = "2.1.21"
